### PR TITLE
added app icon generated by AI and corrected errors on README file

### PR DESCRIPTION
**Pull request by blessingmwiti**

### CODE REVIEW

**Comment by blessingmwiti** [comment]
A screenshot of the app icon
screenshot boot pc

**Comment by SoulForeverInPeace** [comment]
Appreciate a lot :)

i was out of idea regarding the icon

**Review by SoulForeverInPeace — COMMENTED** [review]
in app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml  ```android:drawable="@color/ic_launcher_background"/>``` is missing

**Comment by blessingmwiti** [comment]
> in app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml `android:drawable="@color/ic_launcher_background"/>` is missing

am working on it right away

**Pull request merged**
