### PR TITLE
updated app icon and adding text color

### PR DESCRIPTION
**Pull request by blessingmwiti**

### CODE REVIEW

**Comment by blessingmwiti** [comment]
boot pc

**Comment by blessingmwiti** [comment]
Image used
_4dd147bd-9206-4cb6-86eb-3c63cc4df94a

**Comment by SoulForeverInPeace** [comment]
same thing happened as the last time, icon did not changed. looked into your screenshot again.  did this and that. And lastly figured, should test if my assumption is right. 

looks like not thanks to gtp  both mine and yours time was wasted last time. And yeah roundIcon does what it exactly implies!

**Review by SoulForeverInPeace — APPROVED** [review]

**Comment by blessingmwiti** [comment]
> same thing happened as the last time, icon did not changed. looked into your screenshot again. did this and that. And lastly figured, should test if my assumption is right.
> 
> looks like not thanks to gtp both mine and yours time was wasted last time. And yeah roundIcon does what it exactly implies!

In your end the icon does not change? The ic_background and ic_foreground xml files from @drawable are not needed anymore, maybe we should delete them... and the following line
> @color/ic_launcher_background
is not reflected in colors.xml rather directly in ic_launcher_background.xml under values folder.

**Pull request merged**
